print("Translating RNA into Protein")
f1 = open('entrada/problem9.txt', 'r')
f2 = open('saida/problem9.txt', 'w')

for line in f1:
  for i in range(0, len(line), 3):
    amino = line[i:i+3]
    if amino == "UUU": f2.write("F")
    if amino == "UUC": f2.write("F")
    if amino == "UUA": f2.write("L")
    if amino == "UUG": f2.write("L")
    if amino == "UCU": f2.write("S")
    if amino == "UCC": f2.write("S")
    if amino == "UCA": f2.write("S")
    if amino == "UCG": f2.write("S")
    if amino == "UAU": f2.write("Y")
    if amino == "UAC": f2.write("Y")
    if amino == "UAA": break
    if amino == "UAG": break
    if amino == "UGU": f2.write("C")
    if amino == "UGC": f2.write("C")
    if amino == "UGA": break
    if amino == "UGG": f2.write("W")
    
    if amino == "CUU": f2.write("L")
    if amino == "CUC": f2.write("L")
    if amino == "CUA": f2.write("L")
    if amino == "CUG": f2.write("L")
    if amino == "CCU": f2.write("P")
    if amino == "CCC": f2.write("P")
    if amino == "CCA": f2.write("P")
    if amino == "CCG": f2.write("P")
    if amino == "CAU": f2.write("H")
    if amino == "CAC": f2.write("H")
    if amino == "CAA": f2.write("Q")
    if amino == "CAG": f2.write("Q")
    if amino == "CGU": f2.write("R")
    if amino == "CGC": f2.write("R")
    if amino == "CGA": f2.write("R")
    if amino == "CGG": f2.write("R")
    
    if amino == "AUU": f2.write("I")
    if amino == "AUC": f2.write("I")
    if amino == "AUA": f2.write("I")
    if amino == "AUG": f2.write("M")
    if amino == "ACU": f2.write("T")
    if amino == "ACC": f2.write("T")
    if amino == "ACA": f2.write("T")
    if amino == "ACG": f2.write("T")
    if amino == "AAU": f2.write("N")
    if amino == "AAC": f2.write("N")
    if amino == "AAA": f2.write("K")
    if amino == "AAG": f2.write("K")
    if amino == "AGU": f2.write("S")
    if amino == "AGC": f2.write("S")
    if amino == "AGA": f2.write("R")
    if amino == "AGG": f2.write("R")
    
    if amino == "GUU": f2.write("V")
    if amino == "GUC": f2.write("V")
    if amino == "GUA": f2.write("V")
    if amino == "GUG": f2.write("V")
    if amino == "GCU": f2.write("A")
    if amino == "GCC": f2.write("A")
    if amino == "GCA": f2.write("A")
    if amino == "GCG": f2.write("A")
    if amino == "GAU": f2.write("D")
    if amino == "GAC": f2.write("D")
    if amino == "GAA": f2.write("E")
    if amino == "GAG": f2.write("E")
    if amino == "GGU": f2.write("G")
    if amino == "GGC": f2.write("G")
    if amino == "GGA": f2.write("G")
    if amino == "GGG": f2.write("G")